import Logo1 from "./assets/rlogo/l1.png";
import Test1 from "./assets/tests/test1.png";
import Test2 from "./assets/tests/test2.png";
import Test3 from "./assets/tests/test3.png";
import Test4 from "./assets/tests/test4.png";
import Destination1 from "./assets/materials/dest.jpg";
import Destination2 from "./assets/materials/dest2.jpg";
import GrammarUse from "./assets/materials/inuse.jpg";
import GrammarUse2 from "./assets/materials/esn.jpg";
import OnTheWay from "./assets/materials/ontheway.jpg";
import DestinationB1 from "./assets/books/DestinationB1.pdf";
import DestinationB2 from "./assets/books/destinationb2.pdf";
import English from "./assets/books/English.pdf";
import Ess from "./assets/books/Essential.pdf";
import Way from "./assets/books/way.pdf";
import Olymp1 from "./assets/olimpiads/olimp1.jpg";
import Olymp2 from "./assets/olimpiads/olimp2.jpg";
import Olymp3 from "./assets/olimpiads/olimp3.jpg";
import Olymp4 from "./assets/olimpiads/olimp4.jpg";
import Olymp5 from "./assets/olimpiads/olimp5.jpg";
import Olymp6 from "./assets/olimpiads/olimp6.jpg";
import Olymp7 from "./assets/olimpiads/olimpiads.png";
import Form5 from "./assets/olimpiads/form5.pdf";
import Form6 from "./assets/olimpiads/form6.pdf";
import Form7 from "./assets/olimpiads/form7.pdf";
import Form8 from "./assets/olimpiads/form8.pdf";
import Form9 from "./assets/olimpiads/form9.pdf";


export const materialsData = [
  {
    id: 1,
    title: "Destination B1",
    author1: `Malcolm Mann`,
    author2: `Steve Taylore-Knowles`,
    src: Destination1,
    href: DestinationB1,
  },
  {
    id: 2,
    title: "Destination B2",
    author1: `Malcolm Mann`,
    author2: `Steve Taylore-Knowles`,
    src: Destination2,
    href: DestinationB2,
  },
  {
    id: 3,
    title: "English Grammar in Use",
    author1: ``,
    author2: `Raymond Murphy`,
    src: GrammarUse,
    href: English,
  },
  {
    id: 4,
    title: "Essential Grammar in Use",
    author1: ``,
    author2: `Raymond Murphy`,
    src: GrammarUse2,
    href: Ess,
  },
  {
    id: 5,
    title: "On The Way To Success",
    author1: `E. Karnevskaya`,
    author2: `Z. Kurochkina`,
    src: OnTheWay,
    href: Way,
  },
  //   {
  //     id: 6,
  //     title: "Centralized exam 2024",
  //     author1: ``,
  //     author2: `Aversev`,
  //     src: Testing,
  //     href: Test,
  //   },
];
export const olympiadsData = [
  {
    id: 1,
    title: "Form V",
    author1: ``,
    author2: ``,
    src: Olymp1,
    href: Form5,
  },
  {
    id: 2,
    title: "Form VI",
    author1: ``,
    author2: ``,
    src: Olymp2,
    href: Form6,
  },
  {
    id: 3,
    title: "Form VII",
    author1: ``,
    author2: ``,
    src: Olymp3,
    href: Form7,
  },
  {
    id: 4,
    title: "Form VIII",
    author1: ``,
    author2: ``,
    src: Olymp4,
    href: Form8,
  },
  {
    id: 5,
    title: "Form IX",
    author1: ``,
    author2: ``,
    src: Olymp5,
    href: Form9,
  },
  {
    id: 6,
    title: "Form X",
    author1: ``,
    author2: ``,
    src: Olymp6,
    href: Form9,
  },
  {
    id: 7,
    title: "Form XI",
    author1: ``,
    author2: ``,
    src: Olymp7,
    href: Form9,
  },
];

export const accordionData = [
  {
    id: 1,
    url: Logo1,
    title: "Present Simple",
    description:
      "•	обозначает регулярные действия, привычки, факты, расписание (every day/week/month, always, often, sometimes, rarely, hardly ever, never)",
    paragraf1: "I / you / we / they + V ///he / she / it + Vs",
    paragraf2:
      "+ I drink coffee every day. (Я пью кофе каждый день) – регулярно повторяющееся действие.!!! в 3л.ед.числе (he, she, it) к глаголу прибавляем окончание –s/-es.He drinks coffee every day.!!!",
    paragraf3:
      "- do not (don’t)/ does not (doesn’t)        do(I, you, we, they) / does (he, she, it) I don’t drink coffee every day. (Я не пью кофе каждый день.)She doesn’t drink coffee every day. (Она не пьёт кофе каждый день.)",
    paragraf4:
      "? Does she drink coffee every day? (Она пьёт кофе каждый день?) – Вспомогательный глагол do/does ставится перед подлежащим.",
    paragraf5: "",
  },
  {
    id: 2,
    url: Logo1,
    title: "Present Continuous",
    description: `•	действие, которое происходит сейчас; запланированное действие в будущем (now – сейчас, at the moment – в данный момент). Образуется с помощью вспомогательного глагола to be (am, is, are) и основного глагола c окончанием –ing.`,
    paragraf1: "To be(am, is, are) + Ving",
    paragraf2: "+ I am drinking coffee now. (Я пью кофе сейчас.)",
    paragraf3:
      "- He is not (isn’t) drinking coffee now. (Он не пьёт кофе сейчас.) – К глаголу to be (am, is, are) прибавляется частица not.",
    paragraf4: `? Are you drinking coffee now? (Ты пьёшь кофе сейчас?) – Глагол to be (am, is, are) ставится перед подлежащим.`,
    paragraf5: "",
  },
  {
    id: 3,
    url: Logo1,
    title: "Present Perfect",
    description:
      "•	обозначает действие, произошедшее в прошлом, но важное в настоящем (важен результат в настоящем) (already – уже, just – только что, ever – когда-либо, yet – уже\\ещё, never – никогда, recently – недавно).",
    paragraf1: "have/has + V3/(-ed)",
    paragraf2:
      "+ I have already seen this photo. (Я уже видел эту фотографию.)",
    paragraf3:
      "-  have + not=haven’t  has + not=hasn’t + V3 I haven’t seen this photo yet. ( Я еще не видел эту фотографию.)",
    paragraf4:
      "? Have\\Has ставится перед подлежащим Have you ever seen this photo? ( Ты когда-либо видел эту фотографию?)",
    paragraf5: "",
  },
  {
    id: 4,
    url: Logo1,
    title: "Present Perfect Continuous",
    description:
      "• обозначает действие, которое началось в прошлом и длится до сих пор (since – с , for – на протяжении, all day - весь день, for years – на протяжении лет, recently - недавно)",
    paragraf1: " have/has + been + Ving",
    paragraf2: "+ I have been walking in the park for an hour.",
    paragraf3: "- I haven't been walking in the park for an hour.",
    paragraf4: "? Have you been walking in the park for an hour?",
    paragraf5: "",
  },
  {
    id: 5,
    url: Logo1,
    title: "Past Simple",
    description:
      "•	действие, которое произошло в прошлом (yesterday - вчера, last week – на прошлой неделе, 2 days ago – два дня назад)",
    paragraf1: "V2/ed",
    paragraf2:
      "+ I played football yesterday.(Я играл в футбол вчера). I drank coffee last week.(Я пил кофе на прошлой неделе)",
    paragraf3:
      "- did + not=didn’t / I didn’t play football yesterday. I didn’t drink coffee last week.",
    paragraf4:
      "? Did ставится перед подлежащим. Did you play football yesterday?",
    paragraf5: "",
  },
  {
    id: 6,
    url: Logo1,
    title: "Past Continuous",
    description:
      "•	действия, которые происходили (длились) в какой-то момент или период в прошлом (from … to …, at that time)",
    paragraf1: "was/were + Ving",
    paragraf2: "+ I was walking in the park from 4 to 5 pm yesterday.",
    paragraf3:
      "- wasn't/weren't + Ving / I wasn't walking the dog at that time yesterday",
    paragraf4: "? Were you doing your homework from 6 to 7 pm last Monday?",
    paragraf5: "",
  },
  {
    id: 7,
    url: Logo1,
    title: "Future Simple",
    description:
      "•	действие, которое произойдёт в будущем. (tomorrow - завтра , next week – на следующей неделе , next year – в следующем году )",
    paragraf1: "will + V1",
    paragraf2:
      "+ I will play football tomorrow. (Завтра я буду играть в футбол.)",
    paragraf3:
      "- will + not = won’t / I will not play football tomorrow. ( Завтра я не буду играть в футбол.)",
    paragraf4:
      "? Will ставится перед подлежащим./ Will you play football tomorrow? (Ты будешь играть в футбол завтра?)",
    paragraf5: "",
  },
  {
    id: 8,
    url: Logo1,
    title: "Future Continuous",
    description:
      "•	действия, которые будут происходить в какой-то момент или период в будущем (tomorrow, next, in 5 minutes)",
    paragraf1: "will + be + Ving",
    paragraf2: "+ I will be walking in the park tomorrow morning.",
    paragraf3: "- will not = won't + be + Ving",
    paragraf4: "? Will you be walking in the park tomorrow morning?",
    paragraf5: "",
  },
  {
    id: 9,
    url: Logo1,
    title: "Past Perfect",
    description:
      "•	действие, которое завершилось к определенному моменту в прошлом (by 6 o’clock, by the time,  yet, just, already, before)",
    paragraf1: "had + V3/ed",
    paragraf2:
      "+ By six o’clock Kate had taken down the decorations. Kate had taken down the decorations by the time granny called",
    paragraf3: "- had + not = hadn’t + V3",
    paragraf4: "? Had she taken down the decorations by six o’clock?",
    paragraf5: "",
  },
  {
    id: 10,
    url: Logo1,
    title: "Past Perfect Continuous",
    description:
      "•	действия, которые продолжались до какого-то момента или действия в прошлом(since, for, all day, for years)",
    paragraf1: "had + been + Ving",
    paragraf2:
      "+ I was tired because I had been walking in the park very long.",
    paragraf3:
      "- had + not = hadn’t + been + Ving / I wasn't tired because I hadn't been walking in the park very long.",
    paragraf4: "? Had ____ been + Ving? (Had ставится перед подлежащим)",
    paragraf5: "",
  },
  {
    id: 11,
    url: Logo1,
    title: "Future Perfect",
    description:
      "•	действия, которые произойдут до какого-то момента в будущем (by, tomorrow, next)",
    paragraf1: "will + have + V3/ed",
    paragraf2: "+ I will have walked in the park by 5 pm tomorrow.",
    paragraf3: "- will + not = won't + have + V3/ed",
    paragraf4: "? Will ____ have + V3/ed? (Will ставится перед подлежащим)",
    paragraf5: "",
  },
  {
    id: 12,
    url: Logo1,
    title: "Future Perfect Continuous",
    description:
      "•	действия, которые будут продолжаться до какого-то момента в будущем (by, момент в будущем (on Saturday, at 3 o’clock), tomorrow, next)",
    paragraf1: "will + have + been + Ving",
    paragraf2: "+ At 7 pm I will have been walking in the park for 3 hours.",
    paragraf3: "- will + not = won't + have + been + Ving",
    paragraf4:
      "? Will ____ have + been + Ving? (Will ставится перед подлежащим)",
    paragraf5: "",
  },
  {
    id: 13,
    url: Logo1,
    title: "Few / a few / little / a little",
    description:
      "Few • Означает небольшое количество; • Используется для исчисляемых существительных; • Пример: Few people attended the party.",
    paragraf1: "",
    paragraf2: `A few • Означает \"несколько\" или \"небольшое количество\" • Также используется для исчисляемых существительных \n • Пример: I have a few apples.`,
    paragraf3:
      'Little • Означает "мало" или "очень маленькое количество"; • Используется для неисчисляемых существительных; • Пример: He has little patience.',
    paragraf4:
      'A little • Означает "немного" или "некоторое количество"; • Также используется для неисчисляемых существительных; • Пример: I would like a little coffee.',
    paragraf5:
      'Ключевая разница в том, что "few/a few" применяется к исчисляемым существительным, а "little/a little" к неисчисляемым. Также "few/little" подразумевает меньшее количество, чем "a few/a little".',
  },
];

export const testCards = [
  {
    id: 1,
    title: "Present Simple",
    description: "времена",
    url: Test1,
    quiz: [
      {
        id: 1,
        question: "Martin never ___ me text messages.",
        answers: ["sends", "send", "doesn’t send"],
        answerR: "sends",
      },
      {
        id: 2,
        question: "Tina ___ very happy.",
        answers: ["don’t look", "doesn’t looks", "doesn’t look"],
        answerR: "doesn’t look",
      },
      {
        id: 3,
        question: "The sun ___ in the East.",
        answers: ["rising", "rises", "rise"],
        answerR: "rises",
      },
      {
        id: 4,
        question: "___ many houses?",
        answers: ["Do he owns", "Does he own", "Does he owns"],
        answerR: "Does he own",
      },
      {
        id: 5,
        question: "Where ___ your books?",
        answers: ["do you keep", "you keep", "does you keep"],
        answerR: "do you keep",
      },
      {
        id: 6,
        question: "My parents ___ in a detached house.",
        answers: ["are lived", "lives", "live"],
        answerR: "live",
      },
      {
        id: 7,
        question: "You never ___ what may happen",
        answers: ["knows", "know", "don’t know"],
        answerR: "know",
      },
      {
        id: 8,
        question: "All the companies ___ their goods on TV.",
        answers: ["are advertised", "advertise", "advertises"],
        answerR: "advertise",
      },
      {
        id: 9,
        question: "The bank always ___ on time.",
        answers: ["open", "is open", "opens"],
        answerR: "opens",
      },
      {
        id: 10,
        question: "My mother ___ lots of money on clothes.",
        answers: ["spends", "spend", "don’t spend"],
        answerR: "spends",
      },
      {
        id: 11,
        question: "I ___ too much coffee.",
        answers: ["drink", "drinks", "drinking"],
        answerR: "drink",
      },
      {
        id: 12,
        question: "___ her dog every morning?",
        answers: ["Do Mary walk", "Does Mary walk", "Is Mary walk"],
        answerR: "Does Mary walk",
      },
      {
        id: 13,
        question: "Do you ___ where the post office is?",
        answers: ["know", "knows", "knowing"],
        answerR: "know",
      },
      {
        id: 14,
        question: "I ___ I’ll show you the city.",
        answers: ["promise", "am promise", "promises"],
        answerR: "promise",
      },
      {
        id: 15,
        question: "All sports competitions ___ at our stadium",
        answers: ["takes place", "take place", "are take"],
        answerR: "take place",
      },
      {
        id: 16,
        question: "A surgeon is a person who ___ operations.",
        answers: ["makes", "is make", "make"],
        answerR: "makes",
      },
      {
        id: 17,
        question: "A red traffic light ___ “Stop”.",
        answers: ["is mean", "mean", "means"],
        answerR: "means",
      },
      {
        id: 18,
        question: "___ lunch at work?",
        answers: [
          "Are you usually have",
          "Do you usually have",
          "Does you usually have",
        ],
        answerR: "Do you usually have",
      },
      {
        id: 19,
        question: "They ___ volleyball at weekends.",
        answers: ["doesn’t play", "aren’t play", "don’t play"],
        answerR: "don’t play",
      },
      {
        id: 20,
        question: "___ to you regularly?",
        answers: [
          "Does your relatives write",
          "Do your relatives writes",
          "Do your relatives write",
        ],
        answerR: "Do your relatives write",
      },
      {
        id: 21,
        question: "My grandparents ___ going to the theatre.",
        answers: ["loving", "love", "loves"],
        answerR: "love",
      },
      {
        id: 22,
        question: "This train ___ at 10.30 every day.",
        answers: ["leaves", "does leave", "leave"],
        answerR: "leaves",
      },
      {
        id: 23,
        question: "We ___ for the delay.",
        answers: ["apologize", "apologizes", "apologizing"],
        answerR: "apologize",
      },
      {
        id: 24,
        question: "Ted often ___ in a restaurant.",
        answers: ["is dines", "dine", "dines"],
        answerR: "dines",
      },
      {
        id: 25,
        question: "He ___ to any political party.",
        answers: ["doesn’t belong", "don’t belong", "isn’t belong"],
        answerR: "doesn’t belong",
      },
    ],
  },
  {
    id: 2,
    title: "Present Continuous",
    description: "времена",
    url: Test2,
    quiz: [
      {
        id: 1,
        question: "We ___ four eggs to bake this cake.",
        answers: ["need", "are need", "are needing"],
        answerR: "need",
      },
      {
        id: 2,
        question: "Look! It ___ any more.",
        answers: ["is raining", "isn’t raining", "aren’t raining"],
        answerR: "isn’t raining",
      },
      {
        id: 3,
        question: "He ___ how to use a computer at the moment.",
        answers: ["are learning", "is learn", "is learning"],
        answerR: "is learning",
      },
      {
        id: 4,
        question: "Ron and Michael ___ at the table and doing their homework.",
        answers: ["is sitting", "are siting", "are sitting"],
        answerR: "are sitting",
      },
      {
        id: 5,
        question: "I ___ to find a place to stay at the moment.",
        answers: ["am trying", "trying", "am try"],
        answerR: "am trying",
      },
      {
        id: 6,
        question: "My sister ___ a shower at the moment.",
        answers: ["is having", "is have", "are having"],
        answerR: "is having",
      },
      {
        id: 7,
        question: "Chris ___ in bed with a backache.",
        answers: ["is liing", "is lieing", "is lying"],
        answerR: "is lying",
      },
      {
        id: 8,
        question: "___ in the park right now?",
        answers: ["Is she runing", "Is she running", "Is she run"],
        answerR: "Is she running",
      },
      {
        id: 9,
        question: "Carol is busy. She ___ a letter at the moment.",
        answers: ["is type", "is typing", "is typeing"],
        answerR: "is typing",
      },
      {
        id: 10,
        question: "Andy ___ to Spain this year.",
        answers: ["aren’t going", "isn’t go", "is not going"],
        answerR: "is not going",
      },
      {
        id: 11,
        question: "My dad ___ my bike right now.",
        answers: ["are repairing", "is repairing", "is repair"],
        answerR: "is repairing",
      },
      {
        id: 12,
        question: "My car is broken, so I ___ my mum’s.",
        answers: ["am using", "am use", "is using"],
        answerR: "am using",
      },
      {
        id: 13,
        question: "I ___ what you mean.",
        answers: [
          "am not understand",
          "don’t understand",
          "am not understanding",
        ],
        answerR: "don’t understand",
      },
      {
        id: 14,
        question: "Why ___ I wonder?",
        answers: ["are you crying", "do you crying", "is you crying"],
        answerR: "are you crying",
      },
      {
        id: 15,
        question: "They ___ dinner at the moment.",
        answers: ["is not having", "are not having", "are not have"],
        answerR: "are not having",
      },
      {
        id: 16,
        question: "The students ___ a new project this semester.",
        answers: ["are doing", "is doing", "doing"],
        answerR: "are doing",
      },
      {
        id: 17,
        question: "My parents ___ anything on TV right now.",
        answers: ["aren’t watching", "aren’t watch", "isn’t watching"],
        answerR: "aren’t watching",
      },
      {
        id: 18,
        question: "Marta ___ with other children in her room.",
        answers: ["are playing", "is playing", "playing"],
        answerR: "is playing",
      },
      {
        id: 19,
        question: "___ any languages at the moment?",
        answers: ["Are you studing", "Are you study", "Are you studying"],
        answerR: "Are you studying",
      },
      {
        id: 20,
        question: "___ this birthday party.",
        answers: ["I’m not enjoying", "I’m not enjoing", "I’m not enjoy"],
        answerR: "I’m not enjoying",
      },
      {
        id: 21,
        question: "The population of the country ____.",
        answers: [
          "are constantly increasing",
          "is constantly increase",
          "is constantly increasing",
        ],
        answerR: "is constantly increasing",
      },
      {
        id: 22,
        question: "Both my friend and I ___ today.",
        answers: ["are working", "is working", "am working"],
        answerR: "are working",
      },
      {
        id: 23,
        question: "My brother ___ his own website. It looks great!",
        answers: ["is designing", "are designing", "designing"],
        answerR: "is designing",
      },
      {
        id: 24,
        question: "___ this performance?",
        answers: ["Are you liking", "Do you like", "Do you liking"],
        answerR: "Do you like",
      },
      {
        id: 25,
        question: "___ better?",
        answers: [
          "Are your English getting",
          "Is your English getting",
          "Is your English get",
        ],
        answerR: "Is your English getting",
      },
    ],
  },
  {
    id: 3,
    title: "Present Simple & Continuous",
    description: "времена",
    url: Test3,
    quiz: [
      {
        id: 1,
        question: "Don’t go out! It ___ hard at the moment.",
        answers: [`snows`, `snow`, `is snowing`],
        answerR: "is snowing",
      },
      {
        id: 2,
        question: "We ___ a picnic at the moment.",
        answers: ["has", "are have", "are having"],
        answerR: "are having",
      },
      {
        id: 3,
        question: "Jenny always ___ nice expensive clothes.",
        answers: ["wears", "is wearing", "wear"],
        answerR: "wears",
      },
      {
        id: 4,
        question: "My mother never ___ me up in the morning.",
        answers: ["is making", "wakes", "doesn’t wake"],
        answerR: "wakes",
      },
      {
        id: 5,
        question: "These jeans ___ much.",
        answers: ["are not costing", "don’t cost", "doesn’t cost"],
        answerR: "don’t cost",
      },
      {
        id: 6,
        question: "I ___ dinner because I’m really hungry.",
        answers: ["is cooking", "cook", "am cooking"],
        answerR: "am cooking",
      },
      {
        id: 7,
        question: "We ___ letters to our relatives every month.",
        answers: ["sends", "send", "are sending"],
        answerR: "send",
      },
      {
        id: 8,
        question: "How ___ to work?",
        answers: [
          "do you usually get",
          "are you usually getting",
          "does you usually get",
        ],
        answerR: "do you usually get",
      },
      {
        id: 9,
        question: "Sam and Tim ___ tennis very often.",
        answers: ["don’t play", "are not playing", "doesn’t play"],
        answerR: "don’t play",
      },
      {
        id: 10,
        question: "My father is in Greece now. He ___ at a very nice hotel.",
        answers: ["stays", "is staying", "stay"],
        answerR: "is staying",
      },
      {
        id: 11,
        question: "___ your boyfriend often invite you to the cinema?",
        answers: ["Do", "Is", "Does"],
        answerR: "Does",
      },
      {
        id: 12,
        question: "Mark and Greg always ___ home before 9 p.m.",
        answers: ["comes", "are coming", "come"],
        answerR: "come",
      },
      {
        id: 13,
        question:
          "Their mother can’t fall asleep because the children ___ too much noise.",
        answers: ["make", "are making", "makes"],
        answerR: "are making",
      },
      {
        id: 14,
        question: "Look at that man! ___ him?",
        answers: ["Does you know", "Do you know", "Are you knowing"],
        answerR: "Do you know",
      },
      {
        id: 15,
        question: "His eyes are closed. He ___ at you.",
        answers: ["doesn’t look", "isn’t looking", "isn’t look"],
        answerR: "isn’t looking",
      },
      {
        id: 16,
        question: "My parents ___ the house right now.",
        answers: ["are cleaning", "clean", "is cleaning"],
        answerR: "are cleaning",
      },
      {
        id: 17,
        question: "When ___?",
        answers: [
          "does he normally get up",
          "do he normally get up",
          "is he normally getting up",
        ],
        answerR: "does he normally get up",
      },
      {
        id: 18,
        question: "All children ___ chocolate.",
        answers: ["are adoring", "adore", "are adore"],
        answerR: "adore",
      },
      {
        id: 19,
        question: "Betty can’t answer the phone. She ___.",
        answers: ["sleeps", "is sleeping", "is sleep"],
        answerR: "is sleeping",
      },
      {
        id: 20,
        question: "Ann ___ with her friends early in the morning.",
        answers: [
          "isn’t usually meeting",
          "don’t usually meet",
          "doesn’t usually meet",
        ],
        answerR: "doesn’t usually meet",
      },
      {
        id: 21,
        question: "Brian always ___ his friend in the evening.",
        answers: ["phone", "phones", "is phoning"],
        answerR: "phones",
      },
      {
        id: 22,
        question: "I’m sorry. I ___ this word.",
        answers: ["am not remembering", "doesn’t remember", "don’t remember"],
        answerR: "don’t remember",
      },
      {
        id: 23,
        question: "– Why ___? I’ve lost my keys.",
        answers: ["are you crying", "does you cry", "do you cry"],
        answerR: "are you crying",
      },
      {
        id: 24,
        question: "All the members of our family often ___ for evening tea.",
        answers: ["gathers", "are gathering", "gather"],
        answerR: "gather",
      },
      {
        id: 25,
        question: "What ___ on Saturdays?",
        answers: ["are you doing", "does you do", "do you do"],
        answerR: "do you do",
      },
    ],
  },
  {
    id: 4,
    title: "Past Simple",
    description: "времена",
    url: Test4,
    quiz: [
      {
        id: 1,
        question:
          "My mother was very tired, so she ___ to bed early last night.",
        answers: ["went", "go", "did go"],
        answerR: "went",
      },
      {
        id: 2,
        question: "How much time ___ in Germany last month?",
        answers: ["did you spent", "did you spend", "did you spended"],
        answerR: "did you spend",
      },
      {
        id: 3,
        question: "We ___ a nice time at seaside last summer.",
        answers: ["had", "did have", "haved"],
        answerR: "had",
      },
      {
        id: 4,
        question: "We ___ last night due to the nasty weather.",
        answers: ["didn’t went out", "did go out", "didn’t go out"],
        answerR: "didn’t go out",
      },
      {
        id: 5,
        question: "I ___ the bills last month.",
        answers: ["payed", "didn’t paid", "didn’t pay"],
        answerR: "didn’t pay",
      },
      {
        id: 6,
        question: "I ___ when I was getting off the bus.",
        answers: ["sliped", "slipped", "did slip"],
        answerR: "slipped",
      },
      {
        id: 7,
        question: "Nobody ___ while we were having dinner.",
        answers: ["didn’t phone", "phoned", "did phon"],
        answerR: "phoned",
      },
      {
        id: 8,
        question: "We ___ to sell our old house and buy a new one.",
        answers: ["did decide", "did decided", "decided"],
        answerR: "decided",
      },
      {
        id: 9,
        question: "We ___ a lot last year.",
        answers: ["travelled", "did travel", "did travelled"],
        answerR: "travelled",
      },
      {
        id: 10,
        question: "She ___ French when she was at school.",
        answers: ["studied", "did study", "study"],
        answerR: "studied",
      },
      {
        id: 11,
        question: "Rosa was sleeping when somebody ___ on the door.",
        answers: ["knocked", "did knocked", "did knock"],
        answerR: "knocked",
      },
      {
        id: 12,
        question: "My uncle ___ a yacht last week",
        answers: ["did buy", "bought", "buyed"],
        answerR: "bought",
      },
      {
        id: 13,
        question:
          "It was my brother’s birthday on Sunday, so I ___ him a postcard.",
        answers: ["sended", "send", "sent"],
        answerR: "sent",
      },
      {
        id: 14,
        question: "Who ___ the first airplane?",
        answers: ["invented", "did invent", "did invented"],
        answerR: "invented",
      },
      {
        id: 15,
        question: "It was hot, so I ___ the window.",
        answers: ["did open", "open", "opened"],
        answerR: "opened",
      },
      {
        id: 16,
        question: "My dad ___ when he was little.",
        answers: ["didn’t smoke", "not smoked", "didn’t smoked"],
        answerR: "didn’t smoke",
      },
      {
        id: 17,
        question: "The film was boring. I ___ it.",
        answers: ["enjoy", "didn’t enjoyed", "didn’t enjoy"],
        answerR: "didn’t enjoy",
      },
      {
        id: 18,
        question: "John was so thirsty that he ___ two glasses of water.",
        answers: ["drank", "drink", "drinked"],
        answerR: "drank",
      },
      {
        id: 19,
        question: "___ a new TV program yesterday?",
        answers: ["Did you watched", "Did you watch", "Watched you"],
        answerR: "Did you watch",
      },
      {
        id: 20,
        question: "He never ___ long distances when he was a child.",
        answers: ["didn’t run", "ran", "runned"],
        answerR: "ran",
      },
      {
        id: 21,
        question: "Sandra ___ her English exam successfully yesterday.",
        answers: ["did pass", "pased", "passed"],
        answerR: "passed",
      },
      {
        id: 22,
        question: "___ any museums when you were in England?",
        answers: ["Did you visited", "Visited you", "Did you visit"],
        answerR: "Did you visit",
      },
      {
        id: 23,
        question: "When ___ your new garage?",
        answers: ["you built", "did you build", "did you built"],
        answerR: "did you build",
      },
      {
        id: 24,
        question: "When ___ Maria?",
        answers: ["you last saw", "did you last saw", "did you last see"],
        answerR: "did you last see",
      },
      {
        id: 25,
        question: "My grandfather ___ violin very well when he was young.",
        answers: ["could play", "could played", "can play"],
        answerR: "could play",
      },
    ],
  },
  {
    id: 5,
    title: "Past Continuous",
    description: "времена",
    url: Test2,
    quiz: [
      {
        id: 1,
        question: "They ___ cricket at 10 a.m. yesterday.",
        answers: ["not playing", "weren’t playing", "wasn’t playing"],
        answerR: "weren’t playing",
      },
      {
        id: 2,
        question: "She ___ dinner while her husband was working in the garden.",
        answers: ["was cooking", "were cooking", "was cook"],
        answerR: "was cooking",
      },
      {
        id: 3,
        question: "He __ for me when I came.",
        answers: ["was wait", "were waiting", "was waiting"],
        answerR: "was waiting",
      },
      {
        id: 4,
        question:
          "Carol was at the party last night. She ___ a very nice dress.",
        answers: ["was wearing", "wearing", "were wearing"],
        answerR: "was wearing",
      },
      {
        id: 5,
        question: "The radio was on but nobody ___ to it.",
        answers: ["were listening", "was listening", "weren’t listening"],
        answerR: "was listening",
      },
      {
        id: 6,
        question: "We ___ a New Year tree all morning yesterday.",
        answers: ["was decorating", "were to decorating", "were decorating"],
        answerR: "were decorating",
      },
      {
        id: 7,
        question: "Mary ___ home when she met her old friend.",
        answers: ["was walking", "was walk", "were walking"],
        answerR: "was walking",
      },
      {
        id: 8,
        question: "When I last saw you, you ___ at university.",
        answers: ["was studying", "were studying", "studying"],
        answerR: "were studying",
      },
      {
        id: 9,
        question: "He ___ the house this time yesterday.",
        answers: ["painting", "were painting", "was painting"],
        answerR: "was painting",
      },
      {
        id: 10,
        question:
          "Tom and Liz were busy yesterday. They ___ their mom around the house.",
        answers: ["helping", "was helping", "were helping"],
        answerR: "were helping",
      },
      {
        id: 11,
        question: "Why ___ at you?",
        answers: [
          "was that woman stare",
          "was that woman staring",
          "were that woman staring",
        ],
        answerR: "was that woman staring",
      },
      {
        id: 12,
        question: "Lucy ___ a bath at 9 o’clock yesterday.",
        answers: ["were having", "was have", "was having"],
        answerR: "was having",
      },
      {
        id: 13,
        question:
          "Where were you yesterday evening? I ___ my niece in hospital.",
        answers: ["were visiting", "was visit", "was visiting"],
        answerR: "was visiting",
      },
      {
        id: 14,
        question: "Sam and I ___ over the phone when the connection failed.",
        answers: ["were chatting", "was chatting", "were chat"],
        answerR: "were chatting",
      },
      {
        id: 15,
        question: "___ at 8 p.m. yesterday?",
        answers: ["Knitting she", "Was she knitting", "Were she knitting"],
        answerR: "Was she knitting",
      },
      {
        id: 16,
        question: "We ___ along the coast all evening yesterday.",
        answers: ["were driving", "was driving", "were drive"],
        answerR: "were driving",
      },
      {
        id: 17,
        question: "I didn’t go to work yesterday. I ___ well.",
        answers: ["wasn’t be feel", "wasn’t feeling", "weren’t feeling"],
        answerR: "wasn’t feeling",
      },
      {
        id: 18,
        question: "Kelly was busy, so we ___ very long.",
        answers: ["weren’t staying", "wasn’t stay", "wasn’t staying"],
        answerR: "weren’t staying",
      },
      {
        id: 19,
        question: "We ___ a snowman all morning yesterday.",
        answers: ["were make", "were making", "was making"],
        answerR: "were making",
      },
      {
        id: 20,
        question: "When I met Tim in the shop, he ___ for a new computer.",
        answers: ["was looking", "was look", "were looking"],
        answerR: "was looking",
      },
      {
        id: 21,
        question: "I ___ anything this time yesterday.",
        answers: ["wasn’t doing", "weren’t doing", "not doing"],
        answerR: "wasn’t doing",
      },
      {
        id: 22,
        question: "Sally and Ann ___ in the park when it started raining.",
        answers: ["were running", "were run", "was running"],
        answerR: "were running",
      },
      {
        id: 23,
        question: "Sue ___ outside the theatre when the performance began.",
        answers: ["was to standing", "was standing", "were standing"],
        answerR: "was standing",
      },
      {
        id: 24,
        question: "When I got home, my sister ___ with a kitten.",
        answers: ["was playing", "were playing", "playing"],
        answerR: "was playing",
      },
      {
        id: 25,
        question: "We ___ tea when our grandparents came.",
        answers: ["was having", "were have", "were having"],
        answerR: "were having",
      },
    ],
  },
  {
    id: 6,
    title: "Present Perfect",
    description: "времена",
    url: Test4,
    quiz: [
      {
        id: 1,
        question: "We ___ to France recently.",
        answers: ["has move", "have move", "have moved"],
        answerR: "have moved",
      },
      {
        id: 2,
        question: "Brian ___ his new project yet.",
        answers: ["hasn’t started", "not started", "haven’t started"],
        answerR: "hasn’t started",
      },
      {
        id: 3,
        question: "The students ___ their essays.",
        answers: [
          "have just complete",
          "have just completed",
          "has just completed",
        ],
        answerR: "have just completed",
      },
      {
        id: 4,
        question: "He ___ his cottage yet.",
        answers: ["haven’t sold", "not has sold", "hasn’t sold"],
        answerR: "hasn’t sold",
      },
      {
        id: 5,
        question: "They ___ for the exams yet.",
        answers: ["not prepared", "hasn’t prepared", "haven’t prepared"],
        answerR: "haven’t prepared",
      },
      {
        id: 6,
        question: "Nick ___ a live football match before.",
        answers: ["hasn’t never seen", "have never seen", "has never seen"],
        answerR: "has never seen",
      },
      {
        id: 7,
        question: "___ yet?",
        answers: [
          "Have the rain stopped",
          "Has the rain stop",
          "Has the rain stopped",
        ],
        answerR: "Has the rain stopped",
      },
      {
        id: 8,
        question: "I ___ a computer since I was three.",
        answers: ["has had", "have had", "has have"],
        answerR: "have had",
      },
      {
        id: 9,
        question: "___ your sister with the washing–up?",
        answers: ["Have you help", "Has you helped", "Have you helped"],
        answerR: "Have you helped",
      },
      {
        id: 10,
        question: "Look! The car ___ into the wall.",
        answers: ["have just crashed", "has just crashed", "has just crash"],
        answerR: "has just crashed",
      },
      {
        id: 11,
        question: "She ___ a job so far.",
        answers: ["not has found", "haven’t found", "hasn’t found"],
        answerR: "hasn’t found",
      },
      {
        id: 12,
        question: "Sean ___ his sister in the last few days.",
        answers: ["haven’t seen", "hasn’t saw", "hasn’t seen"],
        answerR: "hasn’t seen",
      },
      {
        id: 13,
        question: "Why ___ so sad recently?",
        answers: ["did he been", "have he been", "has he been"],
        answerR: "has he been",
      },
      {
        id: 14,
        question: "What a pity! Ted ___ his tennis racket.",
        answers: ["has just broken", "have just broken", "just have broken"],
        answerR: "has just broken",
      },
      {
        id: 15,
        question: "Where is your purse? I ___ it.",
        answers: ["have lost", "has lost", "was lost"],
        answerR: "have lost",
      },
      {
        id: 16,
        question: "My wife ___ invitations for the party.",
        answers: ["have already sent", "has already sent", "has already send"],
        answerR: "has already sent",
      },
      {
        id: 17,
        question: "He ___ his work. Why don’t we invite him out?",
        answers: ["has finished", "has finish", "have finished"],
        answerR: "has finished",
      },
      {
        id: 18,
        question: "Lisa and Frank ___ married for two years now.",
        answers: ["have been", "have were", "has been"],
        answerR: "have been",
      },
      {
        id: 19,
        question: "Do we need any tomatoes? No, I ___ some.",
        answers: [
          "has already bought",
          "have already bought",
          "already has bought",
        ],
        answerR: "have already bought",
      },
      {
        id: 20,
        question: "Oxford University Press ___ thousands of books.",
        answers: ["has published", "have published", "was published"],
        answerR: "has published",
      },
      {
        id: 21,
        question: "___ the lottery?",
        answers: ["Have you ever won", "Has you ever won", "Have you ever win"],
        answerR: "Have you ever won",
      },
      {
        id: 22,
        question:
          "Are you going anywhere this summer? Yes, we ___ a trip to Italy.",
        answers: ["have book", "has booked", "have booked"],
        answerR: "have booked",
      },
      {
        id: 23,
        question: "I ___ part in marathons.",
        answers: ["have never taken", "has never taken", "haven’t never taken"],
        answerR: "have never taken",
      },
      {
        id: 24,
        question: "Tom and I ___ friends since childhood.",
        answers: ["have been", "were been", "has been"],
        answerR: "have been",
      },
      {
        id: 25,
        question: "We ___ some furniture for our new flat.",
        answers: [
          "has already chosen",
          "have already chosen",
          "have already chose",
        ],
        answerR: "have already chosen",
      },
    ],
  },
  {
    id: 7,
    title: "Present Perfect Continuous",
    description: "времена",
    url: Test1,
    quiz: [
      {
        id: 1,
        question: "The baby ___ for three hours.",
        answers: ["has been sleeping", "have been sleeping", "been sleeping"],
        answerR: "has been sleeping",
      },
      {
        id: 2,
        question: "My parents ___ the walls all day today.",
        answers: ["has paint", "have been painting", "has been painting"],
        answerR: "have been painting",
      },
      {
        id: 3,
        question: "Donna ___ for a job for half a year.",
        answers: ["has been looking", "have been looking", "has looking"],
        answerR: "has been looking",
      },
      {
        id: 4,
        question: "I ___ about buying new computer since last week.",
        answers: ["has been thinking", "have think", "have been thinking"],
        answerR: "have been thinking",
      },
      {
        id: 5,
        question: "They ___ to mend the tape recorder for an hour.",
        answers: ["has been trying", "have trying", "have been trying"],
        answerR: "have been trying",
      },
      {
        id: 6,
        question: "How long ___ Spanish?",
        answers: [
          "have you been learning",
          "has you been learning",
          "have you been learn",
        ],
        answerR: "have you been learning",
      },
      {
        id: 7,
        question: "I ___ for this company for 5 years.",
        answers: ["have been working", "has been working", "has been work"],
        answerR: "have been working",
      },
      {
        id: 8,
        question: "Liz ___ to ski for a week now.",
        answers: ["has been learning", "have been learning", "has learning"],
        answerR: "has been learning",
      },
      {
        id: 9,
        question: "Sam ___ fish for years.",
        answers: ["has selling", "has been selling", "have been selling"],
        answerR: "has been selling",
      },
      {
        id: 10,
        question: "My mother ___ for the last two hours.",
        answers: ["has been cooking", "have been cooking", "has been cook"],
        answerR: "has been cooking",
      },
      {
        id: 11,
        question: "I ___ to phone you all day.",
        answers: ["have been trying", "has been trying", "have been try"],
        answerR: "have been trying",
      },
      {
        id: 12,
        question: "Stella ___ in the park for half an hour.",
        answers: ["has running", "have been running", "has been running"],
        answerR: "has been running",
      },
      {
        id: 13,
        question: "The children ___ TV since morning.",
        answers: ["have been watching", "have been watch", "has been watching"],
        answerR: "have been watching",
      },
      {
        id: 14,
        question: "We ___ the house since morning.",
        answers: ["have been cleaning", "has been cleaning", "have been clean"],
        answerR: "have been cleaning",
      },
      {
        id: 15,
        question: "How long ___ your homework?",
        answers: [
          "you have been doing",
          "has you been doing",
          "have you been doing",
        ],
        answerR: "have you been doing",
      },
      {
        id: 16,
        question: "Margaret ___ in bed since yesterday.",
        answers: ["have been staying", "has been staying", "been staying"],
        answerR: "has been staying",
      },
      {
        id: 17,
        question: "Your father looks tired. He ___ his car all day.",
        answers: [
          "been repairing",
          "have been repairing",
          "has been repairing",
        ],
        answerR: "has been repairing",
      },
      {
        id: 18,
        question: "My grandpa ___ all his life.",
        answers: ["has been smoke", "has been smoking", "have been smoking"],
        answerR: "has been smoking",
      },
      {
        id: 19,
        question: "How long ___ for us?",
        answers: [
          "have John been waiting",
          "has John been waiting",
          "John has been waiting",
        ],
        answerR: "has John been waiting",
      },
      {
        id: 20,
        question: "How long ___ to music? For a couple of hours.",
        answers: [
          "you have been listening",
          "have you been listening",
          "has you been listening",
        ],
        answerR: "have you been listening",
      },
      {
        id: 21,
        question: "How long ___ singing lessons?",
        answers: [
          "you have been taking",
          "has you been taking",
          "have you been taking",
        ],
        answerR: "have you been taking",
      },
      {
        id: 22,
        question: "We ___ in France for 5 years.",
        answers: ["has been living", "have been living", "have been live"],
        answerR: "have been living",
      },
      {
        id: 23,
        question: "He ___ sick since afternoon.",
        answers: ["has been feeling", "have been feeling", "has feeling"],
        answerR: "has been feeling",
      },
      {
        id: 24,
        question: "Lena ___ geometry since she was 30.",
        answers: ["have been", "has teaching", "has been teaching"],
        answerR: "has been teaching",
      },
      {
        id: 25,
        question: "They ___ billiards for quite a time.",
        answers: ["have been playing", "has been playing", "have been play"],
        answerR: "have been playing",
      },
    ],
  },
  {
    id: 8,
    title: "Past Simple & Continuous",
    description: "времена",
    url: Test4,
    quiz: [
      {
        id: 1,
        question:
          "At the time Jack returned home from England, his father ___ in the Baltic Sea.",
        answers: ["was sailing", "sailed", "were sailing"],
        answerR: "was sailing",
      },
      {
        id: 2,
        question: "We were in a difficult situation. We ___ what to do.",
        answers: ["didn’t know", "were not knowing", "not know"],
        answerR: "didn’t know",
      },
      {
        id: 3,
        question: "Kelly ___ near the river at 4 p.m. yesterda",
        answers: ["sunbathed", "was sunbathing", "were sunbathing"],
        answerR: "was sunbathing",
      },
      {
        id: 4,
        question: "The editor of the magazine ___ to print the article.",
        answers: ["wasn’t allowing", "weren’t allowing", "didn’t allow"],
        answerR: "didn’t allow",
      },
      {
        id: 5,
        question: "Agatha Christie ___ a lot of detective stories.",
        answers: ["were writing", "was writing", "wrote"],
        answerR: "wrote",
      },
      {
        id: 6,
        question: "What ___ at 6 p.m. yesterday?",
        answers: ["did you do", "were you doing", "was you doing"],
        answerR: "were you doing",
      },
      {
        id: 7,
        question: "Madonna ___ popular when she was young.",
        answers: ["was becoming", "became", "was become"],
        answerR: "became",
      },
      {
        id: 8,
        question: "The firm went bankrupt and I ___ my job.",
        answers: ["lost", "was losing", "losing"],
        answerR: "lost",
      },
      {
        id: 9,
        question: "I felt sick yesterday. I ___ something rotten.",
        answers: ["were eating", "ate", "was eating"],
        answerR: "ate",
      },
      {
        id: 10,
        question: "I ___ for the way out of the centre but couldn’t find it.",
        answers: ["were looking", "was looking", "looked"],
        answerR: "was looking",
      },
      {
        id: 11,
        question: "Why ___ for so long yesterday?",
        answers: [
          "did the baby cry",
          "was the baby crying",
          "did the baby crying",
        ],
        answerR: "was the baby crying",
      },
      {
        id: 12,
        question: "My grandma ___ apple trees while she lived in the country.",
        answers: ["planted", "was planting", "were planting"],
        answerR: "was planting",
      },
      {
        id: 13,
        question: "Which exams ___ at school?",
        answers: ["were you taking", "did you took", "did you take"],
        answerR: "did you take",
      },
      {
        id: 14,
        question: "Where ___ when I met you yesterday?",
        answers: ["did you went", "did you going", "were you going"],
        answerR: "were you going",
      },
      {
        id: 15,
        question: "The train ___ on time yesterday",
        answers: ["arrived", "was arrive", "was arriving"],
        answerR: "arrived",
      },
      {
        id: 16,
        question: "The bike is ok now. My dad ___ it yesterday.",
        answers: ["was repair", "were repairing", "repaired"],
        answerR: "repaired",
      },
      {
        id: 17,
        question: "When ___ lobsters?",
        answers: [
          "did you last eat",
          "did you last eating",
          "was you last eating",
        ],
        answerR: "did you last eat",
      },
      {
        id: 18,
        question:
          "– Why is the dog so hungry?– I ___ it yesterday night. It was sick.",
        answers: ["didn’t feed", "didn’t fed", "wasn’t feeding"],
        answerR: "didn’t feed",
      },
      {
        id: 19,
        question:
          "Darrel couldn’t find his old hat. His sister ___ it away long time ago.",
        answers: ["was throwing", "throwed", "threw"],
        answerR: "threw",
      },
      {
        id: 20,
        question: "Greg ___ in a test when his teacher noticed it.",
        answers: ["cheated", "was cheat", "was cheating"],
        answerR: "was cheating",
      },
      {
        id: 21,
        question: "We ___ climbing in the mountains last summer.",
        answers: ["went", "were going", "did go"],
        answerR: "went",
      },
      {
        id: 22,
        question: "Kate ___ along the country road when her car broke down.",
        answers: ["was drive", "drove", "was driving"],
        answerR: "was driving",
      },
      {
        id: 23,
        question:
          "He usually meets his sister on Fridays but he ___ her last Friday.",
        answers: ["didn’t visit", "wasn’t visiting", "weren’t visiting"],
        answerR: "didn’t visit",
      },
      {
        id: 24,
        question: "Titanic ___ in the Atlantic many years ago.",
        answers: ["sank", "sinked", "was sinking"],
        answerR: "sank",
      },
      {
        id: 25,
        question: "I ___ to be a pilot when I was young.",
        answers: ["was wanted", "was wanting", "wanted"],
        answerR: "wanted",
      },
    ],
  },
  {
    id: 9,
    title: "Present Perfect & Past Simple",
    description: "времена",
    url: Test3,
    quiz: [
      {
        id: 1,
        question: "My uncle ___ anything last month.",
        answers: ["haven’t earned", "hasn’t earned", "didn’t earn"],
        answerR: "didn’t earn",
      },
      {
        id: 2,
        question: "I ___ my best friend for ten years.",
        answers: ["knew", "have known", "has known"],
        answerR: "have known",
      },
      {
        id: 3,
        question: "My sister ___ her ankle yesterday evening.",
        answers: ["have twisted", "twisted", "has twisted"],
        answerR: "twisted",
      },
      {
        id: 4,
        question: "Michael ___ to play the piano last year.",
        answers: ["learned", "has learnt", "have learnt"],
        answerR: "learned",
      },
      {
        id: 5,
        question: "Sandra ___ her bike yesterday.",
        answers: ["has fallen off", "have fallen off", "fell off"],
        answerR: "fell off",
      },
      {
        id: 6,
        question: "I ___ this college since September.",
        answers: ["attended", "has attended", "have attended"],
        answerR: "have attended",
      },
      {
        id: 7,
        question: "Somebody ___ our car last Sunday.",
        answers: ["has stolen", "stole", "have stolen"],
        answerR: "stole",
      },
      {
        id: 8,
        question: "___ their wedding last weekend?",
        answers: [
          "Has they celebrated",
          "Did they celebrate",
          "Have they celebrated",
        ],
        answerR: "Did they celebrate",
      },
      {
        id: 9,
        question: "My brother ___ a lot when he was young.",
        answers: ["has swum", "have swum", "swam"],
        answerR: "swam",
      },
      {
        id: 10,
        question: "I ___ a letter. Can you post it?",
        answers: ["have just written", "just wrote", "has just written"],
        answerR: "have just written",
      },
      {
        id: 11,
        question: "She ___ much progress in her career so far.",
        answers: ["hasn’t made", "haven’t made", "didn’t make"],
        answerR: "hasn’t made",
      },
      {
        id: 12,
        question: "I don’t want to go to the cinema. I ___ this film.",
        answers: ["have already seen", "already saw", "has already seen"],
        answerR: "have already seen",
      },
      {
        id: 13,
        question: "How is Lucy? Fine, we ___ her on our way home.",
        answers: ["just met", "have just met", "has just met"],
        answerR: "have just met",
      },
      {
        id: 14,
        question: "Chris ___ a truck before.",
        answers: ["hasn’t never driven", "has never driven", "never drove"],
        answerR: "has never driven",
      },
      {
        id: 15,
        question: "_ diving?",
        answers: [
          "When have you last gone",
          "When did you last go",
          "When did you last went",
        ],
        answerR: "When did you last go",
      },
      {
        id: 16,
        question: "He ___ a good education in London three years ago.",
        answers: ["received", "has received", "have received"],
        answerR: "received",
      },
      {
        id: 17,
        question: "Columbus ___ America in the 15th century.",
        answers: ["has discovered", "have discovered", "discovered"],
        answerR: "discovered",
      },
      {
        id: 18,
        question: "Is Mary at home? No, she ___.",
        answers: ["just left", "have just left", "has just left"],
        answerR: "has just left",
      },
      {
        id: 19,
        question: "Listen to me! I ___ with the solution.",
        answers: ["just came up", "have just came up", "have just come up"],
        answerR: "have just come up",
      },
      {
        id: 20,
        question: "Sally ___ her relatives for a very long time.",
        answers: ["hasn’t seen", "haven’t seen", "didn’t see"],
        answerR: "hasn’t seen",
      },
      {
        id: 21,
        question: "My parents ___ to Germany in 2005.",
        answers: ["went", "has gone", "have gone"],
        answerR: "went",
      },
      {
        id: 22,
        question:
          "Do you want something to drink? No, thanks. I ___ a cup of tea.",
        answers: ["just had", "have just had", "has just had"],
        answerR: "have just had",
      },
      {
        id: 23,
        question: "Andy ___ to Japan twice.",
        answers: ["have been", "has been", "was"],
        answerR: "has been",
      },
      {
        id: 24,
        question: "___ a cherry pie?",
        answers: [
          "Has your mom ever baked",
          "Did your mom ever bake",
          "Have your mom ever baked",
        ],
        answerR: "Has your mom ever baked",
      },
      {
        id: 25,
        question: "Mark ___ the car race last year.",
        answers: ["hasn’t won", "haven’t won", "didn’t win"],
        answerR: "didn’t win",
      },
    ],
  },
  {
    id: 10,
    title: "Present Perfect Continuous & Simple",
    description: "времена",
    url: Test2,
    quiz: [
      {
        id: 1,
        question: "Cathy ___ since 2 o’clock. She is exhausted.",
        answers: ["has been driving", "has driven", "have been driving"],
        answerR: "has been driving",
      },
      {
        id: 2,
        question: "My friends and I ___ since 2 o’clock.",
        answers: [
          "have been sunbathing",
          "has been sunbathing",
          "have sunbathed",
        ],
        answerR: "have been sunbathing",
      },
      {
        id: 3,
        question: "Jane is abroad. She ___ three countries.",
        answers: [
          "has already been visiting",
          "have already visited",
          "has already visited",
        ],
        answerR: "has already visited",
      },
      {
        id: 4,
        question: "Where have you been? Mom ___ for you all day.",
        answers: ["has been looking", "have been looking", "has looked"],
        answerR: "has been looking",
      },
      {
        id: 5,
        question: "He ___ in London for two weeks now.",
        answers: ["has stayed", "have been staying", "has been staying"],
        answerR: "has been staying",
      },
      {
        id: 6,
        question: "We ___ to the theatre since last month.",
        answers: ["haven’t been", "haven’t gone", "hasn’t been"],
        answerR: "haven’t been",
      },
      {
        id: 7,
        question: "___ many people to our wedding ceremony?",
        answers: [
          "Have you invited",
          "Have you been inviting",
          "Has you invited",
        ],
        answerR: "Have you invited",
      },
      {
        id: 8,
        question: "We ___ to such a big park before.",
        answers: ["haven’t never been", "has never been", "have never been"],
        answerR: "have never been",
      },
      {
        id: 9,
        question: "How long ___ this research?",
        answers: [
          "have you been making",
          "has you been making",
          "have you made",
        ],
        answerR: "have you been making",
      },
      {
        id: 10,
        question: "I ___ to go scuba diving.",
        answers: [
          "have always been wanting",
          "has always wanted",
          "have always wanted",
        ],
        answerR: "have always wanted",
      },
      {
        id: 11,
        question: "___ dancing lessons?",
        answers: [
          "Has you ever taken",
          "Have you ever taken",
          "Has you ever been taking",
        ],
        answerR: "Have you ever taken",
      },
      {
        id: 12,
        question: "___ the latest news?",
        answers: ["Have you been hearing", "Has you heard", "Have you heard"],
        answerR: "",
      },
      {
        id: 13,
        question: "We ___ the rent yet.",
        answers: ["haven’t paid", "haven’t been paying", "hasn’t paid"],
        answerR: "haven’t paid",
      },
      {
        id: 14,
        question: "Den ___ championships before.",
        answers: [
          "has never won",
          "has never been winning",
          "hasn’t never won",
        ],
        answerR: "has never won",
      },
      {
        id: 15,
        question: "My uncle is a doctor. He ___ lots of vital operations.",
        answers: ["has been making", "has made", "have made"],
        answerR: "has made",
      },
      {
        id: 16,
        question: "I want to buy a new flat. I ___ money for ages.",
        answers: ["have been saving", "have saved", "has been saving"],
        answerR: "have been saving",
      },
      {
        id: 17,
        question: "___ books for a long time?",
        answers: [
          "Have you written",
          "Has you been writing",
          "Have you been writing",
        ],
        answerR: "Have you been writing",
      },
      {
        id: 18,
        question: "Jack is cold. He ___ for too long.",
        answers: ["have been swimming", "has been swimming", "has swum"],
        answerR: "has been swimming",
      },
      {
        id: 19,
        question: "Bob ___ his new pencil case.",
        answers: [
          "have already lost",
          "has already lost",
          "has already been losing",
        ],
        answerR: "has already lost",
      },
      {
        id: 20,
        question: "It’s the first time Martin ___ ill.",
        answers: ["have fallen", "has fallen", "has been falling"],
        answerR: "has fallen",
      },
      {
        id: 21,
        question: "My eyes are tired. I ___ since afternoon.",
        answers: ["have read", "have been reading", "has been reading"],
        answerR: "have been reading",
      },
      {
        id: 22,
        question: "I don’t want to go out. The cold wind ___ since morning.",
        answers: ["have been blowing", "has blown", "has been blowing"],
        answerR: "has been blowing",
      },
      {
        id: 23,
        question: "We ___ in this café before.",
        answers: ["haven’t been eating", "haven’t eaten", "hasn’t eaten"],
        answerR: "haven’t eaten",
      },
      {
        id: 24,
        question: "Sally ___ news since she left university.",
        answers: ["have reported", "has been reporting", "has reported"],
        answerR: "has been reporting",
      },
      {
        id: 25,
        question: "Marta __ in the shopping centre for 2 hours.",
        answers: ["has being", "has been", "have been"],
        answerR: "has been",
      },
    ],
  },
  {
    id: 11,
    title: "Past Perfect Continuous & Simple",
    description: "времена",
    url: Test4,
    quiz: [
      {
        id: 1,
        question: "Claire said she ___ her sister since last month.",
        answers: ["hadn’t phoned", "not had phoned", "hadn’t phoning"],
        answerR: "hadn’t phoned",
      },
      {
        id: 2,
        question:
          "They ___ the same restaurant for years before they found a better one.",
        answers: ["had been visit", "had been visiting", "had visited"],
        answerR: "had been visiting",
      },
      {
        id: 3,
        question: "We ___ for half an hour when Dan finally joined us.",
        answers: ["had eaten", "had been eating", "had eating"],
        answerR: "had been eating",
      },
      {
        id: 4,
        question:
          "When I arrived, Lucy ___ in bed with temperature since lunchtime.",
        answers: ["had been lying", "had lying", "had lied"],
        answerR: "had been lying",
      },
      {
        id: 5,
        question: "I ___ the golf club before Martin did it.",
        answers: ["had been joining", "had joined", "had been join"],
        answerR: "had joined",
      },
      {
        id: 6,
        question:
          "Sam ___ to go to the wedding but he couldn’t take a day off work.",
        answers: ["had wanted", "had want", "had been wanting"],
        answerR: "had wanted",
      },
      {
        id: 7,
        question: "The film ___ when we came to the cinema.",
        answers: [
          "had already begun",
          "had already been beginning",
          "had already been begun",
        ],
        answerR: "had already begun",
      },
      {
        id: 8,
        question:
          "I was extremely unhappy to have lost my watch. I ___ it for a very long time.",
        answers: ["had been having", "had had", "had been had"],
        answerR: "had had",
      },
      {
        id: 9,
        question: "I was glad to meet Ted again. I ___ him for ages.",
        answers: ["not had seen", "had been seeing", "hadn’t seen"],
        answerR: "hadn’t seen",
      },
      {
        id: 10,
        question: "Mary insisted that she ___ the ring from the drawer.",
        answers: ["hadn’t been taking", "not had been taking", "hadn’t taken"],
        answerR: "hadn’t taken",
      },
      {
        id: 11,
        question: "I didn’t see Jim yesterday. He ___ abroad.",
        answers: ["had been going", "had been gone", "had gone"],
        answerR: "had gone",
      },
      {
        id: 12,
        question: "My mom ___ dinner when I returned home.",
        answers: [
          "had already cooked",
          "had already been",
          "had already cooking",
        ],
        answerR: "had already cooked",
      },
      // {
      //   id: 13,
      //   question: "",
      //   answers: ["", "", ""],
      //   answerR: "",
      // },
      // {
      //   id: 14,
      //   question: "",
      //   answers: ["", "", ""],
      //   answerR: "",
      // },
      // {
      //   id: 15,
      //   question: "",
      //   answers: ["", "", ""],
      //   answerR: "",
      // },
      // {
      //   id: 16,
      //   question: "",
      //   answers: ["", "", ""],
      //   answerR: "",
      // },
      // {
      //   id: 17,
      //   question: "",
      //   answers: ["", "", ""],
      //   answerR: "",
      // },
      // {
      //   id: 18,
      //   question: "",
      //   answers: ["", "", ""],
      //   answerR: "",
      // },
      // {
      //   id: 19,
      //   question: "",
      //   answers: ["", "", ""],
      //   answerR: "",
      // },
      // {
      //   id: 20,
      //   question: "",
      //   answers: ["", "", ""],
      //   answerR: "",
      // },
      // {
      //   id: 21,
      //   question: "",
      //   answers: ["", "", ""],
      //   answerR: "",
      // },
      // {
      //   id: 22,
      //   question: "",
      //   answers: ["", "", ""],
      //   answerR: "",
      // },
      // {
      //   id: 23,
      //   question: "",
      //   answers: ["", "", ""],
      //   answerR: "",
      // },
      // {
      //   id: 24,
      //   question: "",
      //   answers: ["", "", ""],
      //   answerR: "",
      // },
      // {
      //   id: 25,
      //   question: "",
      //   answers: ["", "", ""],
      //   answerR: "",
      // },
    ],
  },
  {
    id: 12,
    title: "Ways of expressing the future",
    description: "времена",
    url: Test3,
    quiz: [
      {
        id: 1,
        question: "The plane ___ at 10 tomorrow morning.",
        answers: ["is going to land", "lands", "is landing"],
        answerR: "lands",
      },
      {
        id: 2,
        question: "Mary ___ her parents this evening.",
        answers: ["will visit", "is visiting", "visit"],
        answerR: "is visiting",
      },
      {
        id: 3,
        question: "I ___ paint my living room green.",
        answers: ["am going to", "am", "will be"],
        answerR: "am going to",
      },
      {
        id: 4,
        question: "Linda ___ a massage at 5 this evening.",
        answers: ["will have", "has", "is having"],
        answerR: "is having",
      },
      {
        id: 5,
        question: "I’m thirsty. I think I ___ a glass of water.",
        answers: ["am having", "will have", "am going to have"],
        answerR: "will have",
      },
      {
        id: 6,
        question: "What time ___? At 9 in the evening.",
        answers: [
          "is the performance going to begin",
          "is the performance beginning",
          "does the performance begin",
        ],
        answerR: "does the performance begin",
      },
      {
        id: 7,
        question: "Jerry and Carol ___ married next Saturday.",
        answers: ["will getting", "are getting", "get"],
        answerR: "are getting",
      },
      {
        id: 8,
        question: "Look! The sky is dark. It ___.",
        answers: ["is going to snow", "will snow", "snows"],
        answerR: "is going to snow",
      },
      {
        id: 9,
        question: "I promise I ___ to the party without you.",
        answers: ["not go", "don’t go", "won’t go"],
        answerR: "won’t go",
      },
      {
        id: 10,
        question: "It’s very cold in here. Oh, I ___ the window.",
        answers: ["am closing", "close", "will close"],
        answerR: "will close",
      },
      {
        id: 11,
        question: "I promise I ___ of your dog.",
        answers: ["am taking care", "am going to take care", "will take care"],
        answerR: "will take care",
      },
      {
        id: 12,
        question: "It’s very cold today, so Tom ___ on a winter coat.",
        answers: ["is putting", "is going to put", "will put"],
        answerR: "is going to put",
      },
      {
        id: 13,
        question: "A new swimming pool ___ on 10 June.",
        answers: ["is opening", "opens", "is going to open"],
        answerR: "opens",
      },
      {
        id: 14,
        question: "The seminar ___ at 8 a.m. on Monday.",
        answers: ["is starting", "is going to start", "starts"],
        answerR: "starts",
      },
      {
        id: 15,
        question: "I expect you ___ the exam.",
        answers: ["will pass", "are passing", "are going to pass"],
        answerR: "will pass",
      },
      {
        id: 16,
        question: "We ___ for dinner at 3 p.m. today.",
        answers: ["are meeting", "meet", "will meet"],
        answerR: "are meeting",
      },
      {
        id: 17,
        question:
          "Eveline ___ at her granny for a couple of days. They arranged it long ago.",
        answers: ["will stay", "is staying", "stays"],
        answerR: "is staying",
      },
      {
        id: 18,
        question: "Try this dress! I’m sure it ___ you.",
        answers: ["will suit", "is going to suit", "suits"],
        answerR: "will suit",
      },
      {
        id: 19,
        question: "The working day has already started. ___ type her report?",
        answers: ["Will she", "Is she going to", "Does she"],
        answerR: "Is she going to",
      },
      {
        id: 20,
        question: "I’m sure it ___ hot tomorrow.",
        answers: ["will be", "is", "is being"],
        answerR: "will be",
      },
      {
        id: 21,
        question: "This film is awful. We ___ watch it.",
        answers: ["are not going to", "don’t", "not going"],
        answerR: "are not going to",
      },
      {
        id: 22,
        question: "There isn’t any juice left. I ___ some.",
        answers: ["will get", "get", "am getting"],
        answerR: "will get",
      },
      {
        id: 23,
        question: "Mike ___ ping-pong with his father on Friday evening.",
        answers: ["is playing", "going to play", "will play"],
        answerR: "is playing",
      },
      {
        id: 24,
        question: "Holidays are coming. ___ any interesting places?",
        answers: ["Do you visit", "Are you visiting", "Are you going to visit"],
        answerR: "Are you going to visit",
      },
      {
        id: 25,
        question: "Our train ___ in Moscow at 6 tomorrow morning.",
        answers: ["arrives", "is going to arrive", "is arriving"],
        answerR: "arrives",
      },
    ],
  },
  {
    id: 13,
    title: "Infinitive & Gerund",
    description: "герундий",
    url: Test1,
    quiz: [
      {
        id: 1,
        question: "We usually learn ___ at school.",
        answers: ["reading", "read", "to read"],
        answerR: "to read",
      },
      {
        id: 2,
        question: "What are you going to do after ___ school?",
        answers: ["finishing", "to finish", "to finishing"],
        answerR: "finishing",
      },
      {
        id: 3,
        question: "Don’t forget ___ everything I asked for.",
        answers: ["to buying", "buying", "to buy"],
        answerR: "to buy",
      },
      {
        id: 4,
        question: "I can remember ___ into the river when I was ten.",
        answers: ["falling", "to fall", "fall"],
        answerR: "falling",
      },
      {
        id: 5,
        question: "Have you ever thought of ___ your own fruit and vegetables?",
        answers: ["grow", "growing", "to grow"],
        answerR: "growing",
      },
      {
        id: 6,
        question: "His language skills seem ___.",
        answers: ["to be improving", "improve", "to improving"],
        answerR: "to be improving",
      },
      {
        id: 7,
        question: "Mike warned his sister not ___ back late.",
        answers: ["come", "to come", "to coming"],
        answerR: "to come",
      },
      {
        id: 8,
        question: "Andrew hates ___ early in the morning.",
        answers: ["getting up", "to getting up", "to get up"],
        answerR: "getting up",
      },
      {
        id: 9,
        question: "Sandra managed ___ a solution.",
        answers: ["finding", "find", "to find"],
        answerR: "to find",
      },
      {
        id: 10,
        question: "Ken failed ___ new friends at school.",
        answers: ["to make", "making", "to making"],
        answerR: "to make",
      },
      {
        id: 11,
        question: "Lucy can’t imagine herself ___ a lorry.",
        answers: ["to driving", "driving", "to drive"],
        answerR: "driving",
      },
      {
        id: 12,
        question: "We can’t risk ___ our flight.",
        answers: ["to miss", "to missing", "missing"],
        answerR: "missing",
      },
      {
        id: 13,
        question: "I prefer ___ outdoor games.",
        answers: ["to play", "to playing", "playing"],
        answerR: "to play",
      },
      {
        id: 14,
        question: "All children enjoy ___ sweets.",
        answers: ["to eat", "to eating", "eating"],
        answerR: "eating",
      },
      {
        id: 15,
        question: "I can’t stand ___ in the countryside.",
        answers: ["to live", "living", "to living"],
        answerR: "living",
      },
      {
        id: 16,
        question: "We arranged ___ back home on 10 June.",
        answers: ["return", "returning", "to return"],
        answerR: "to return",
      },
      {
        id: 17,
        question: "Nick promised ___ everything secret.",
        answers: ["keeping", "to keep", "keep"],
        answerR: "to keep",
      },
      {
        id: 18,
        question: "Ann didn’t know what ___.",
        answers: ["answer", "to answer", "answering"],
        answerR: "to answer",
      },
      {
        id: 19,
        question: "I would like ___ Brazil this summer.",
        answers: ["visit", "visiting", "to visit"],
        answerR: "to visit",
      },
      {
        id: 20,
        question: "Sam hopes ___ an academic scholarship.",
        answers: ["to get", "get", "getting"],
        answerR: "to get",
      },
      {
        id: 21,
        question: "My dad gave up ___ a long time ago.",
        answers: ["smoking", "to smoke", "smoke"],
        answerR: "smoking",
      },
      {
        id: 22,
        question: "George practices ___twice a week.",
        answers: ["to swimming", "to swim", "swimming"],
        answerR: "swimming",
      },
      {
        id: 23,
        question: "Mark insists on ___ a picnic this Sunday.",
        answers: ["to having", "have", "having"],
        answerR: "having",
      },
      {
        id: 24,
        question: "Dave agreed ___ his friends at the café tomorrow evening.",
        answers: ["to meet", "to meeting", "meet"],
        answerR: "to meet",
      },
      {
        id: 25,
        question: "We decided ___ home as it was raining hard.",
        answers: ["stay", "to stay", "staying"],
        answerR: "to stay",
      },
    ],
  },
  {
    id: 14,
    title: "Interrogative sentences",
    description: "вопросы",
    url: Test3,
    quiz: [
      {
        id: 1,
        question: "___ Ann got a dress for the party?",
        answers: ["Does", "Has", "Have"],
        answerR: "Has",
      },
      {
        id: 2,
        question: "___ was the TV invented?",
        answers: ["What", "Who", "When"],
        answerR: "When",
      },
      {
        id: 3,
        question: "___ turn is to clean the room?",
        answers: ["Which", "Whose", "Who"],
        answerR: "Whose",
      },
      {
        id: 4,
        question: "___ do you need this bucket for?",
        answers: ["What", "Where", "Why"],
        answerR: "What",
      },
      {
        id: 5,
        question:
          "___ your father take part in the organization of the competition last week?",
        answers: ["Does", "Had", "Did"],
        answerR: "Did",
      },
      {
        id: 6,
        question: "Could you explain how ___?",
        answers: [
          "this device work",
          "this device works",
          "does this device work",
        ],
        answerR: "this device works",
      },
      {
        id: 7,
        question: "Do you have ___ interest in biology?",
        answers: ["some", "many", "any"],
        answerR: "any",
      },
      {
        id: 8,
        question: "How ___ stars are there in the sky?",
        answers: ["more", "many", "much"],
        answerR: "many",
      },
      {
        id: 9,
        question: "Who usually ___ the dishes in your family?",
        answers: ["do", "does", "is doing"],
        answerR: "does",
      },
      {
        id: 10,
        question: "Alfred always writes long essays, ___?",
        answers: ["doesn’t he", "does he", "don’t he"],
        answerR: "doesn’t he",
      },
      {
        id: 11,
        question: "___ there any new books on sale?",
        answers: ["Is", "Do", "Are"],
        answerR: "Are",
      },
      {
        id: 12,
        question: "She never watches talk shows, ___?",
        answers: ["doesn’t she", "does she", "don’t she"],
        answerR: "does she",
      },
      {
        id: 13,
        question: "Did he know where ___her holidays last summer?",
        answers: [
          "his sister has spent",
          "did his sister spend",
          "his sister had spent",
        ],
        answerR: "his sister had spent",
      },
      {
        id: 14,
        question: "___ married next Saturday?",
        answers: ["Do they get", "Are they getting", "Will they get"],
        answerR: "Are they getting",
      },
      {
        id: 15,
        question: "___ a CD player?",
        answers: ["Have Jill got", "Have Jill", "Has Jill got"],
        answerR: "Has Jill got",
      },
      {
        id: 16,
        question: "What ___ the main points of this report?",
        answers: ["do", "are", "is"],
        answerR: "are",
      },
      {
        id: 17,
        question: "___ Cathy lately?",
        answers: ["Have you seen", "Did you see", "Has you seen"],
        answerR: "Have you seen",
      },
      {
        id: 18,
        question: "Who ___ Ben lately?",
        answers: ["has seen", "had saw", "have seen"],
        answerR: "has seen",
      },
      {
        id: 19,
        question: "___ colour is your new suit?",
        answers: ["Where", "Why", "What"],
        answerR: "What",
      },
      {
        id: 20,
        question: "___ she phoned you before you got home?",
        answers: ["Has", "Have", "Had"],
        answerR: "Had",
      },
      {
        id: 21,
        question: "___ a dog under the table?",
        answers: ["Are", "Are there", "Is there"],
        answerR: "Is there",
      },
      {
        id: 22,
        question: "Andy can’t skate very well, ___?",
        answers: ["can’t he", "can he", "could he"],
        answerR: "can he",
      },
      {
        id: 23,
        question: "How ___ do you want for your old car?",
        answers: ["much", "many", "a lot"],
        answerR: "much",
      },
      {
        id: 24,
        question: "Tim didn’t go to the football match yesterday, ___?",
        answers: ["did he", "does he", "didn’t he"],
        answerR: "did he",
      },
      {
        id: 25,
        question: "___ influenced your choice of profession?",
        answers: ["What", "When", "Which"],
        answerR: "What",
      },
    ],
  },
  {
    id: 15,
    title: "Сonditional sentences",
    description: "условные",
    url: Test4,
    quiz: [
      {
        id: 1,
        question: "If Mark ___ so much, he would be fit.",
        answers: ["didn’t ate", "won’t eat", "didn’t eat"],
        answerR: "didn’t eat",
      },
      {
        id: 2,
        question: "If he had phoned me, I ___ him the home task.",
        answers: ["told", "would tell", "would have told"],
        answerR: "would have told",
      },
      {
        id: 3,
        question: "If Sue ___ anybody the news, it won’t be a secret.",
        answers: ["tells", "had told", "told"],
        answerR: "tells",
      },
      {
        id: 4,
        question: "If I see Jill, I ___ her to call you.",
        answers: ["has reminded", "will remind", "would remind"],
        answerR: "will remind",
      },
      {
        id: 5,
        question: "If I found a purse, I ___ it back to the owner.",
        answers: ["will give", "would give", "had given"],
        answerR: "would give",
      },
      {
        id: 6,
        question: "If I were you, I ___ about the incident.",
        answers: [
          "hadn’t have worried",
          "wouldn’t have worry",
          "wouldn’t worry",
        ],
        answerR: "wouldn’t worry",
      },
      {
        id: 7,
        question: "I wish I ___ in the countryside. (but I don’t)",
        answers: ["would live", "live", "lived"],
        answerR: "lived",
      },
      {
        id: 8,
        question: "If I knew his address, I ___ him.",
        answers: ["visited", "would visit", "had visited"],
        answerR: "would visit",
      },
      {
        id: 9,
        question: "I ___ in case I am not right.",
        answers: ["has apologized", "would apologize", "will apologize"],
        answerR: "will apologize",
      },
      {
        id: 10,
        question: "If she had been taking care of her health, she ___ ill.",
        answers: ["wouldn’t have fell", "didn’t fall", "wouldn’t have fallen"],
        answerR: "wouldn’t have fallen",
      },
      {
        id: 11,
        question: "If Mark ___ for the job, he would have got it.",
        answers: ["applies", "will apply", "had applied"],
        answerR: "had applied",
      },
      {
        id: 12,
        question: "I wish I ___ in the test. (but I did)",
        answers: ["hadn’t cheated", "didn’t cheat", "wouldn’t cheat"],
        answerR: "hadn’t cheated",
      },
      {
        id: 13,
        question:
          "They’ll go to the restaurant if they ___ a table in advance.",
        answers: ["reserved", "reserve", "would reserve"],
        answerR: "reserve",
      },
      {
        id: 14,
        question: "If he hadn’t asked for the directions, we ___ lost.",
        answers: ["may got", "might have got", "might has got"],
        answerR: "might have got",
      },
      {
        id: 15,
        question: "We will stay at this hotel provided it ___ much.",
        answers: ["hadn’t cost", "didn’t cost", "doesn’t cost"],
        answerR: "doesn’t cost",
      },
      {
        id: 16,
        question:
          "If Tom ___ the bus, he would have come to the meeting on time.",
        answers: ["hasn’t missed", "missed", "hadn’t missed"],
        answerR: "hadn’t missed",
      },
      {
        id: 17,
        question: "If Mike joined the studio, he ___ a great dancer.",
        answers: ["had become", "would become", "will become"],
        answerR: "would become",
      },
      {
        id: 18,
        question:
          "If John ___ the local race, he will take part in the national championship.",
        answers: ["would win", "wins", "won"],
        answerR: "wins",
      },
      {
        id: 19,
        question:
          "If Jack hadn’t passed all the exams, he ___ from university.",
        answers: [
          "wouldn’t have graduated",
          "didn’t graduate",
          "hadn’t graduated",
        ],
        answerR: "wouldn’t have graduated",
      },
      {
        id: 20,
        question: "If I were you, I ___ the red dress.",
        answers: ["had chosen", "would choose", "choose"],
        answerR: "would choose",
      },
      {
        id: 21,
        question:
          "We would have been injured in the crash if we ___ seatbelts.",
        answers: ["hasn’t been wearing", "hadn’t been wearing", "wore"],
        answerR: "hadn’t been wearing",
      },
      {
        id: 22,
        question: "We’ll miss you a lot in case you ___ to another house.",
        answers: ["move", "would move", "will move"],
        answerR: "move",
      },
      {
        id: 23,
        question:
          "If you hadn’t left your camera at home, we ___ lots of pictures.",
        answers: ["could took", "took", "could have taken"],
        answerR: "could have taken",
      },
      {
        id: 24,
        question: "I won’t believe you unless you ___ clear evidence.",
        answers: ["had given", "will give", "give"],
        answerR: "give",
      },
      {
        id: 25,
        question: "If it were not for the snow, we ___ the car to the cinema.",
        answers: ["can drive", "could drive", "can drive"],
        answerR: "could drive",
      },
    ],
  },
  {
    id: 16,
    title: "Noun",
    description: "существительное",
    url: Test2,
    quiz: [
      {
        id: 1,
        question: "Ted has always got lots of ___.",
        answers: ["problem", "the problems", "problems"],
        answerR: "problems",
      },
      {
        id: 2,
        question: "Do you hear that terrible ___?",
        answers: ["a noise", "noises", "noise"],
        answerR: "noise",
      },
      {
        id: 3,
        question: "Cheetah is ___ fastest animal in the world.",
        answers: ["a", "—", "the"],
        answerR: "the",
      },
      {
        id: 4,
        question: "Have you found ___ pen yet?",
        answers: ["—", "a", "the"],
        answerR: "a",
      },
      {
        id: 5,
        question: "All ___ envelopes must have stamps on them.",
        answers: ["the", "an", "—"],
        answerR: "—",
      },
      {
        id: 6,
        question: "I want ___ dress I saw in the boutique yesterday.",
        answers: ["the", "—", "a"],
        answerR: "the",
      },
      {
        id: 7,
        question: "Would you like to have ___ lunch at a café?",
        answers: ["the", "a", "—"],
        answerR: "—",
      },
      {
        id: 8,
        question: "Jack usually sleeps in his ___.",
        answers: ["pyjamases", "pyjama", "pyjamas"],
        answerR: "pyjamas",
      },
      {
        id: 9,
        question: "I need ___ new pair of trousers.",
        answers: ["the", "a", "—"],
        answerR: "a",
      },
      {
        id: 10,
        question: "These two ___ are relatives.",
        answers: ["woman", "women", "womans"],
        answerR: "women",
      },
      {
        id: 11,
        question: "I would appreciate if you buy ___ of bread.",
        answers: ["a loaf", "a tin", "a bowl"],
        answerR: "a loaf",
      },
      {
        id: 12,
        question: "Does this expression make ___ sense?",
        answers: ["the", "a", "—"],
        answerR: "—",
      },
      {
        id: 13,
        question: "What does the government do to help ___ poor?",
        answers: ["the", "—", "a"],
        answerR: "the",
      },
      {
        id: 14,
        question: "Can you smell ___ gas in the kitchen?",
        answers: ["—", "a", "the"],
        answerR: "—",
      },
      {
        id: 15,
        question: "Albert Einstein was ___ scientist.",
        answers: ["a", "—", "the"],
        answerR: "a",
      },
      {
        id: 16,
        question: "I’m sure there are ___ in the forest.",
        answers: ["a lot of deers", "a lot of deer", "the deer"],
        answerR: "a lot of deer",
      },
      {
        id: 17,
        question: "Could you buy ___ packet of juice, please?",
        answers: ["a", "—", "the"],
        answerR: "a",
      },
      {
        id: 18,
        question: "Can you pass me ___ salt, please?",
        answers: ["—", "the", "a"],
        answerR: "the",
      },
      {
        id: 19,
        question: "His uncle is in ___ prison for smuggling.",
        answers: ["a", "—", "the"],
        answerR: "—",
      },
      {
        id: 20,
        question: "Whose are those ___?",
        answers: ["photoes", "photos", "photo"],
        answerR: "photos",
      },
      {
        id: 21,
        question: "There ___ much milk in the jug.",
        answers: ["aren’t", "are", "isn’t"],
        answerR: "isn’t",
      },
      {
        id: 22,
        question: "Can you imagine our life without ___?",
        answers: ["electricity", "an electricity", "electricities"],
        answerR: "electricity",
      },
      {
        id: 23,
        question: "The jury hasn’t made ___ decision yet.",
        answers: ["a", "—", "the"],
        answerR: "a",
      },
      {
        id: 24,
        question: "I’d like to have ___ of chocolate with my tea.",
        answers: ["a bars", "a bar", "bar"],
        answerR: "a bar",
      },
      {
        id: 25,
        question: "My grandparents are really nice ___.",
        answers: ["persons", "peoples", "people"],
        answerR: "people",
      },
    ],
  },
  //  {
  //    id: 17,
  //    title: "",
  //    description: "времена",
  //    url: Test4,
  //    quiz: [
  //      {
  //        id: 1,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 2,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 3,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 4,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 5,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 6,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 7,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 8,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 9,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 10,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 11,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 12,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 13,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 14,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 15,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 16,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 17,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 18,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 19,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 20,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 21,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 22,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 23,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 24,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 25,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //    ],
  //  },
  //  {
  //    id: 18,
  //    title: "",
  //    description: "времена",
  //    url: Test4,
  //    quiz: [
  //      {
  //        id: 1,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 2,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 3,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 4,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 5,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 6,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 7,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 8,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 9,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 10,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 11,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 12,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 13,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 14,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 15,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 16,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 17,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 18,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 19,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 20,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 21,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 22,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 23,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 24,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 25,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //    ],
  //  },
  //  {
  //    id: 19,
  //    title: "",
  //    description: "времена",
  //    url: Test4,
  //    quiz: [
  //      {
  //        id: 1,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 2,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 3,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 4,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 5,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 6,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 7,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 8,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 9,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 10,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 11,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 12,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 13,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 14,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 15,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 16,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 17,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 18,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 19,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 20,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 21,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 22,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 23,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 24,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //      {
  //        id: 25,
  //        question: "",
  //        answers: ["", "", ""],
  //        answerR: "",
  //      },
  //    ],
  //  },
];
